### ISSUE TITLE
v2.25.10 seems to not work on my machine (2.25.7 works)

### ISSUE THREAD

**Issue by akavel** [0install/0publish-gui-dotnet#87]
After the initial choice window (new empty feed, wizard, open existing feed), whether I choose "new empty feed" or "open existing feed" (didn't try wizard), the app quits, and doesn't display the feed editor window. I can attach some debug logs if needed, but I don't know where to find them.

I used 0install main GUI to try running an older version - the next one from the list (2.25.7) opened fine via "open existing feed".

**Comment by bastianeicher** [comment]
Thanks for reporting this issue.

Fixed the problem in 01d34e1ec19d256c9adc126519b328eabfa28147.

I've released 2.25.11 with the fix and marked 2.25.10 as buggy.

**Comment by akavel** [comment]
Thank you! :)
